In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Model Building

In [41]:
df_dummies = pd.read_csv('training.csv')

In [45]:
df_dummies.head()

,Number_of_Referrals,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Customer_Status,Gender_Female,Gender_Male,...,Payment_Method_Bank Withdrawal,Payment_Method_Credit Card,Payment_Method_Mailed Check,Age_group_18-30,Age_group_31-50,Age_group_51-70,Age_group_70+,Tenure_group_1-12,Tenure_group_13-24,Tenure_group_25-36
0,5,75.150002,3480.350098,0.0,0,422.549988,3902.899902,0,0,1,...,0,1,0,0,0,0,1,1,0,0
1,9,50.250000,2221.550049,0.0,0,292.049988,2513.600098,0,0,1,...,0,1,0,0,1,0,0,1,0,0
2,15,71.800003,1167.800049,0.0,0,734.400024,1902.199951,1,0,1,...,1,0,0,0,0,0,1,0,1,0
3,14,78.949997,378.399994,0.0,0,61.349998,439.750000,1,1,0,...,1,0,0,0,0,0,1,0,1,0
4,2,69.099998,3168.000000,0.0,0,1466.479980,4634.479980,0,1,0,...,0,1,0,0,1,0,0,0,0,1

In [196]:
!pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Requirement already satisfied: imbalanced-learn in c:\users\nikhi\anaconda3\lib\site-packages (from imblearn) (0.12.3)
Requirement already satisfied: numpy>=1.17.3 in c:\users\nikhi\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in c:\users\nikhi\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.13.1)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\nikhi\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.5.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\nikhi\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\nikhi\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (3.5.0)
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Installing collected packages: imblearn
Successfully installed imblearn-0.0

In [244]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from imblearn.combine import SMOTEENN
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,accuracy_score

X = df_dummies.drop('Customer_Status',axis=1)
y = df_dummies['Customer_Status']

In [260]:
#Upsampling minority classes
sm = SMOTEENN()
Xs, ys = sm.fit_resample(X,y)

X_train_sm,X_test_sm,y_train_sm,y_test_sm = train_test_split(Xs,ys,test_size=0.2,random_state=2)
#print(X_train_sm.shape,y_train_sm.shape)

X_train_sm_scaled = X_train_sm.copy() 
X_test_sm_scaled = X_test_sm.copy()

X_train_sm_scaled[num_cols] = scaler.fit_transform(X_train_sm[num_cols]) 

X_test_sm_scaled[num_cols] = scaler.transform(X_test_sm[num_cols])

In [212]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)
print(X_train.shape,y_train.shape)

(4805, 79) (4805,)

In [ ]:
scaler = MinMaxScaler()

num_cols=['Number_of_Referrals','Monthly_Charge','Total_Charges','Total_Refunds',
         'Total_Extra_Data_Charges','Total_Long_Distance_Charges','Total_Revenue']

X_train_scaled = X_train.copy() 
X_test_scaled = X_test.copy()

X_train_scaled[num_cols] = scaler.fit_transform(X_train[num_cols]) 

X_test_scaled[num_cols] = scaler.transform(X_test[num_cols])

In [230]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [232]:
y_pred=rf.predict(X_test)

In [248]:
print(rf.score(X_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred,labels=[0,1]))

1.0
0.8544093178036606
              precision    recall  f1-score   support

           0       0.87      0.93      0.90       858
           1       0.79      0.67      0.72       344

    accuracy                           0.85      1202
   macro avg       0.83      0.80      0.81      1202
weighted avg       0.85      0.85      0.85      1202

In [258]:
##Scaled + Original model

rf = RandomForestClassifier()
rf.fit(X_train_scaled,y_train)

y_pred=rf.predict(X_test_scaled)

print("Score :",rf.score(X_test_scaled,y_pred))
print("Accuracy :",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred,labels=[0,1]))

Score : 1.0
Accuracy : 0.8552412645590682
              precision    recall  f1-score   support

           0       0.87      0.93      0.90       858
           1       0.80      0.66      0.72       344

    accuracy                           0.86      1202
   macro avg       0.84      0.80      0.81      1202
weighted avg       0.85      0.86      0.85      1202

In [256]:
## Upsampling one model
rf_sm = RandomForestClassifier()

rf_sm.fit(X_train_sm,y_train_sm)
y_pred_sm=rf_sm.predict(X_test_sm)

print("Score :",rf_sm.score(X_test_sm,y_pred_sm))
print("Accuracy :",accuracy_score(y_test_sm,y_pred_sm))
print(classification_report(y_test_sm,y_pred_sm,labels=[0,1]))

Score : 1.0
Accuracy : 0.9548577036310107
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       471
           1       0.95      0.96      0.96       548

    accuracy                           0.95      1019
   macro avg       0.96      0.95      0.95      1019
weighted avg       0.95      0.95      0.95      1019

In [268]:
## SMOTEENN + Scaled params

rf_sm.fit(X_train_sm_scaled,y_train_sm)
y_pred_sm=rf_sm.predict(X_test_sm_scaled)

print("Score :",rf_sm.score(X_test_sm_scaled,y_pred_sm))
print("Accuracy :",accuracy_score(y_test_sm,y_pred_sm))
print(confusion_matrix(y_test_sm,y_pred_sm))
print(classification_report(y_test_sm,y_pred_sm,labels=[0,1]))

Score : 1.0
Accuracy : 0.9628180039138943
[[443  19]
 [ 19 541]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       462
           1       0.97      0.97      0.97       560

    accuracy                           0.96      1022
   macro avg       0.96      0.96      0.96      1022
weighted avg       0.96      0.96      0.96      1022

### predicting on joined customer who are likely to churn ahead

In [271]:
test = pd.read_excel(file_path, sheet_name='vw_JoinData')

final_test = test.copy()
customer_ids = test['Customer_ID']

test.head()

,Customer_ID,Gender,Age,Married,State,Number_of_Referrals,Tenure_in_Months,Value_Deal,Phone_Service,Multiple_Lines,...,Payment_Method,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Customer_Status,Churn_Category,Churn_Reason
0,13744-AND,Female,41,Yes,Andhra Pradesh,8,3,Deal 5,Yes,No,...,Bank Withdrawal,19.650000,19.650000,0.0,0,13.85,33.500000,Joined,Others,Others
1,13823-TEL,Female,31,Yes,Telangana,1,28,Deal 5,No,No,...,Bank Withdrawal,24.500000,46.400002,0.0,0,0.00,46.400002,Joined,Others,Others
2,13946-HAR,Female,41,Yes,Haryana,1,3,Deal 5,Yes,No,...,Credit Card,19.650000,19.650000,0.0,0,23.67,43.320000,Joined,Others,Others
3,14567-TAM,Male,43,No,Tamil Nadu,1,9,NaN,Yes,No,...,Credit Card,20.350000,20.350000,0.0,0,44.09,64.440002,Joined,Others,Others
4,16244-UTT,Female,19,Yes,Uttar Pradesh,5,7,NaN,Yes,No,...,Credit Card,19.549999,19.549999,0.0,0,5.10,24.650000,Joined,Others,Others

In [299]:
final_test['Value_Deal'].value_counts()

Value_Deal
Deal 5    160
Name: count, dtype: int64

In [ ]:
# replacing missing values
test['Value_Deal'].fillna("No Deal", inplace=True)
test['Internet_Type'].fillna(test['Internet_Type'].mode()[0], inplace=True)

# binnig age and tenure
test['Age_group'] = test['Age'].apply(binning_age)

labels = ['{0}-{1}'.format(i,i+11) for i in range(1,36,12)]
test['Tenure_group'] = pd.cut(test.Tenure_in_Months,range(1,40,12),labels=labels)

# dropping columns
test.drop(columns=['Customer_ID','Age','Tenure_in_Months','Churn_Category','Churn_Reason','Customer_Status'],axis=1,inplace=True)

# dummifying object columns
test_dummy = pd.get_dummies(test,dtype='int')

# adding dummy columns from training data for consistency
dummy_columns = [col for col in X_train_sm_scaled.columns] # getting all columns with name Value_Deal from training set

for col in dummy_columns:                                                         # adding absent columns in test data 
    if col not in test_dummy.columns:
        test_dummy[col] = 0

test_dummy = test_dummy[X_train_sm_scaled.columns]                                # to ensure same order as training data



# normalizing numeric columns 
num_cols=['Number_of_Referrals','Monthly_Charge','Total_Charges','Total_Refunds',
         'Total_Extra_Data_Charges','Total_Long_Distance_Charges','Total_Revenue']

test_dummy[num_cols] = scaler.transform(test_dummy[num_cols])

In [293]:
test_dummy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 411 entries, 0 to 410
Data columns (total 75 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Number_of_Referrals             411 non-null    float64
 1   Monthly_Charge                  411 non-null    float64
 2   Total_Charges                   411 non-null    float64
 3   Total_Refunds                   411 non-null    float64
 4   Total_Extra_Data_Charges        411 non-null    float64
 5   Total_Long_Distance_Charges     411 non-null    float64
 6   Total_Revenue                   411 non-null    float64
 7   Gender_Female                   411 non-null    int32
 8   Gender_Male                     411 non-null    int32
 9   Married_No                      411 non-null    int32
 10  Married_Yes                     411 non-null    int32
 11  State_Andhra Pradesh            411 non-null    int32
 12  State_Assam                     411 non-null    int32
 13  State_Bihar                     411 non-null    int32
 14  State_Chhattisgarh              411 non-null    int32
 15  State_Delhi                     411 non-null    int32
 16  State_Gujarat                   411 non-null    int32
 17  State_Haryana                   411 non-null    int32
 18  State_Jammu & Kashmir           411 non-null    int32
 19  State_Jharkhand                 411 non-null    int32
 20  State_Karnataka                 411 non-null    int32
 21  State_Kerala                    411 non-null    int32
 22  State_Madhya Pradesh            411 non-null    int32
 23  State_Maharashtra               411 non-null    int32
 24  State_Odisha                    411 non-null    int32
 25  State_Puducherry                411 non-null    int32
 26  State_Punjab                    411 non-null    int32
 27  State_Rajasthan                 411 non-null    int32
 28  State_Tamil Nadu                411 non-null    int32
 29  State_Telangana                 411 non-null    int32
 30  State_Uttar Pradesh             411 non-null    int32
 31  State_Uttarakhand               411 non-null    int32
 32  State_West Bengal               411 non-null    int32
 33  Value_Deal_Deal 5               411 non-null    int32
 34  Value_Deal_No Deal              411 non-null    int32
 35  Phone_Service_No                411 non-null    int32
 36  Phone_Service_Yes               411 non-null    int32
 37  Multiple_Lines_No               411 non-null    int32
 38  Multiple_Lines_Yes              411 non-null    int32
 39  Internet_Service_No             411 non-null    int32
 40  Internet_Service_Yes            411 non-null    int32
 41  Internet_Type_Cable             411 non-null    int32
 42  Internet_Type_DSL               411 non-null    int32
 43  Internet_Type_Fiber Optic       411 non-null    int32
 44  Online_Security_No              411 non-null    int32
 45  Online_Security_Yes             411 non-null    int32
 46  Online_Backup_No                411 non-null    int32
 47  Online_Backup_Yes               411 non-null    int32
 48  Device_Protection_Plan_No       411 non-null    int32
 49  Device_Protection_Plan_Yes      411 non-null    int32
 50  Premium_Support_No              411 non-null    int32
 51  Premium_Support_Yes             411 non-null    int32
 52  Streaming_TV_No                 411 non-null    int32
 53  Streaming_TV_Yes                411 non-null    int32
 54  Streaming_Movies_No             411 non-null    int32
 55  Streaming_Movies_Yes            411 non-null    int32
 56  Streaming_Music_No              411 non-null    int32
 57  Streaming_Music_Yes             411 non-null    int32
 58  Unlimited_Data_No               411 non-null    int32
 59  Unlimited_Data_Yes              411 non-null    int32
 60  Contract_Month-to-Month         411 non-null    int32
 61  Contract_One Year               411 non-null    int32
 62  Contract_Two Year               411 non-null    int32
 63  Paperless_Billing_No            411 non-null    int32
 64  Paperless_Billing_Yes           411 non-null    int32
 65  Payment_Method_Bank Withdrawal  411 non-null    int32
 66  Payment_Method_Credit Card      411 non-null    int32
 67  Payment_Method_Mailed Check     411 non-null    int32
 68  Age_group_18-30                 411 non-null    int32
 69  Age_group_31-50                 411 non-null    int32
 70  Age_group_51-70                 411 non-null    int32
 71  Age_group_70+                   411 non-null    int32
 72  Tenure_group_1-12               411 non-null    int32
 73  Tenure_group_13-24              411 non-null    int32
 74  Tenure_group_25-36              411 non-null    int32
dtypes: float64(7), int32(68)
memory usage: 131.8 KB

In [321]:
predictions = rf_sm.predict(test_dummy)

In [323]:
final_test['Predicted Customer_Status'] = predictions

In [329]:
final_test

,Customer_ID,Gender,Age,Married,State,Number_of_Referrals,Tenure_in_Months,Value_Deal,Phone_Service,Multiple_Lines,...,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Customer_Status,Churn_Category,Churn_Reason,Predicted Customer_Status
0,13744-AND,Female,41,Yes,Andhra Pradesh,8,3,Deal 5,Yes,No,...,19.650000,19.650000,0.0,0,13.850000,33.500000,Joined,Others,Others,1
1,13823-TEL,Female,31,Yes,Telangana,1,28,Deal 5,No,No,...,24.500000,46.400002,0.0,0,0.000000,46.400002,Joined,Others,Others,1
2,13946-HAR,Female,41,Yes,Haryana,1,3,Deal 5,Yes,No,...,19.650000,19.650000,0.0,0,23.670000,43.320000,Joined,Others,Others,1
3,14567-TAM,Male,43,No,Tamil Nadu,1,9,NaN,Yes,No,...,20.350000,20.350000,0.0,0,44.090000,64.440002,Joined,Others,Others,1
4,16244-UTT,Female,19,Yes,Uttar Pradesh,5,7,NaN,Yes,No,...,19.549999,19.549999,0.0,0,5.100000,24.650000,Joined,Others,Others,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406,99144-UTT,Female,41,No,Uttar Pradesh,9,20,NaN,Yes,No,...,19.650000,68.349998,0.0,0,106.769997,175.119995,Joined,Others,Others,0
407,97828-MAH,Female,57,No,Maharashtra,0,12,Deal 5,Yes,No,...,92.000000,266.799988,0.0,0,46.799999,313.600006,Joined,Others,Others,1
408,99855-MAH,Female,50,Yes,Maharashtra,5,29,NaN,Yes,No,...,69.699997,135.199997,0.0,0,31.340000,166.539993,Joined,Others,Others,1
409,99862-BIH,Female,30,No,Bihar,12,9,Deal 5,Yes,No,...,74.000000,74.000000,0.0,0,23.700001,97.699997,Joined,Others,Others,1
410,99996-HAR,Male,22,Yes,Haryana,2,8,Deal 5,Yes,No,...,53.549999,53.549999,0.0,0,16.059999,69.610001,Joined,Others,Others,1

In [337]:
final = final_test[final_test['Predicted Customer_Status']==1]

final.to_csv(r'C:\Users\Nikhi\Churn-Prediction(SQL-BI-PY-ML)\final_pred.csv', index=False)